package com.aianik.anik.ai.common.dto.agent;

import com.aianik.anik.ai.common.model.ConfigExtAttrsDTO;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * Chat dispatch request
 *
 * @author openanik
 * @date 2025-04-08
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ChatDispatchRequest {
    
    /** Request ID */
    private String requestId;

    /** Tracking ID (generated by admin, passed through the agent side) */
    private String traceId;

    /** Root observation SPAN ID for the entire interaction (created server-side; client agent_execution should attach under this node) */
    private String rootSpanId;
    
    /** Agent configuration */
    private AgentConfig agentConfig;
    
    /** User info */
    private UserInfo userInfo;
    
    /** Session ID */
    private String conversationId;
    
    /** User messages */
    private String userMessage;
    
    /** Model configuration */
    private ModelConfig modelConfig;
    
    /** MCP service list */
    private List<McpServerDescriptor> mcpServers;
    
    /** Skill list*/
    private List<SkillDescriptor> skills;
    
    /** historical news */
    private List<HistoryMessage> historyMessages;
    
    /** Memory context */
    private String memoryContext;
    
    /** system prompt word*/
    private String systemPrompt;

    /**
     * Server web port
     */
    private Integer serverHttpPort;
    
    /**
     * Agent configuration
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AgentConfig {
        private Long agentId;
        private String name;
        private String instruction;
        private Boolean mcpEnabled;
        private Boolean skillEnabled;
        private Boolean ragEnabled;
        private Boolean memoryEnabled;
        private Long memoryConfigId;
        private Long embeddingModelId;
        private Long ragId;
    }
    
    /**
     * User info
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class UserInfo {
        private Long userId;
        private String userName;
        private String openId;
    }
    
    /**
     * Model configuration
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ModelConfig {
        private String modelKey;
        private String apiEndpoint;
        private String apiKey;
        private ConfigExtAttrsDTO configJson;
    }
    
    /**
     * MCP service descriptor
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class McpServerDescriptor {
        private Long id;
        private String name;
        private Integer transportType;
        private String baseUri;
        private String endpoint;
        private String command;
        private List<String> args;
        private Map<String, String> envVars;
        private Integer authType;
        private Map<String, String> authConfig;
    }
    
    /**
     * Skill descriptor
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class SkillDescriptor {
        private Long id;
        private String name;
        private String description;
        private String version;
        /** Full Skill content such as SKILL.md */
        private String skillPrompt;
    }
    
    /**
     * historical news
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class HistoryMessage {
        private String role;
        private String content;
    }
}
