package com.aizuda.anik.ai.feature.agent.chain;

import com.aizuda.anik.ai.ClientInstanceManager;
import com.aizuda.anik.ai.persistence.admin.po.UserPO;
import com.aizuda.anik.ai.persistence.agent.po.AgentPO;
import com.aizuda.anik.ai.persistence.mcp.po.McpServerPO;
import com.google.common.collect.Lists;
import lombok.Data;
import org.springframework.ai.tool.ToolCallback;
import org.springframework.web.servlet.mvc.method.annotation.ResponseBodyEmitter;
import com.aizuda.anik.ai.common.dto.agent.ChatDispatchRequest;

import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * The agent dialogue responsibility chain context is transferred between Handlers and gradually filled in.
 */
@Data
public class AgentChatContext {

    // ── Input (fixed during construction)──
    private final Long agentId;
    private final String conversationId;
    private final String content;
    private final ResponseBodyEmitter emitter;
    /**
     * Explicitly passed in request user in OpenAPI scenario (null in non-OpenAPI scenario)
     */
    private final UserPO requestUser;
    /**
     * OpenId explicitly passed in in OpenAPI scenario (empty in non-OpenAPI scenario)
     */
    private final String openId;

    /**
     * List of MCP service IDs for userDisable
     */
    private List<Long> disabledMcpServerIds;
    /**
     * Skill ID list of userDisable
     */
    private List<Long> disabledSkillIds;

    /**
     * Set to true when the preceding Handler has failed and ended the response, and subsequent Handlers should be short-circuited.
     */
    private boolean terminated;

    /**
     * Tracking ID, generated by AgentChatService, throughout the entire conversation link
     */
    private String traceId;

    /**
     * Root observation SPAN ID for the entire interaction (covering from HTTP request to response completion), generated by AgentChatService
     */
    private String rootSpanId;

    /**
     * root SPAN start time (epoch millis), generated by AgentChatService
     */
    private Long rootSpanStartTimeMs;

    /**
     * Whether gRPC streaming distribution has been started (used to distinguish synchronization failure from asynchronous callback ending)
     */
    private boolean streamDispatchStarted;

    /**
     * Whether the root SPAN has been closed to avoid concurrent repeated writing
     */
    private final AtomicBoolean rootSpanClosed = new AtomicBoolean(false);

    /**
     * Context Preparation SPAN ID, generated by InitContextHandler, is used to associate configuration and deliver sub-observations
     */
    private String contextPreparationSpanId;

    // ── Filled in by each Handler in turn ──
    private UserPO user;
    private AgentPO agent;
    private Long modelId;
    private String systemPrompt;
    private List<McpServerPO> mcpServers = Lists.newArrayList();
    private List<ToolCallback> toolCallbacks = Lists.newArrayList();

    // ── Remotely distribute and transmit data (filled by the corresponding Handler and assembled uniformly by LlmCallHandler)──

    /**
     * Model configuration (including decrypted API Key) — ModelResolveHandler
     */
    private ChatDispatchRequest.ModelConfig modelConfig;

    /**
     * MCP Service Descriptor (with built-in RAG MCP) - McpHandler
     */
    private List<ChatDispatchRequest.McpServerDescriptor> mcpServerDescriptors = Lists.newArrayList();

    /**
     * Skill descriptor (including skillContent) — SkillAgentChatHandler
     */
    private List<ChatDispatchRequest.SkillDescriptor> skillDescriptors = Lists.newArrayList();

    /**
     * Historical messages — ContextCollectorHandler
     */
    private List<ChatDispatchRequest.HistoryMessage> historyMessages = Lists.newArrayList();

    /**
     * Long-term memory context — ContextCollectorHandler
     */
    private String memoryContext;

    /**
     * Target Client — ContextCollectorHandler
     */
    private ClientInstanceManager.ClientInstanceInfo targetClient;
}
